import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar";
import NavBar from "@/components/NavBar";
import Providers from "@/lib/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-[#FAFAFA] dark:bg-[#0D062D]`}>
        <Providers>
          <main className="flex relative">
            <SideBar />
            <div className="w-full relative">
              <NavBar />
              <div className="h-full w-full flex items-start">
                {children}
              </div>
            </div>
          </main>

        </Providers>
      </body>
    </html>
  );
}
